"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0b@(zrnd2p3%b-!$w2t&7jb6*1v&xf+l0h39@8su$4w91s&ve0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "django.contrib.gis",   
    'users',
    'fire',
    'frontend',

]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

JWT_SECRET_KEY = SECRET_KEY
JWT_ALGORITHM = "HS256"
JWT_ACCESS_TTL_MINUTES = 60

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("DB_NAME", "crisis_db"),
        "USER": os.getenv("DB_USER", "crisis_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", "crisis_pass"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

import os

# 2-3 line explanation:
# We read MinIO/GeoServer settings from environment variables injected by docker-compose (.env/env_file).
# This block supports BOTH legacy env names (GEOSERVER_INTERNAL_BASE_URL, GEOSERVER_USER, ...)
# and newer aliases (GEOSERVER_BASE_URL_INTERNAL, GEOSERVER_ADMIN_USER, ...), without duplicate overrides.

def _env(*keys, default=None):
    for k in keys:
        v = os.getenv(k)
        if v is not None and str(v).strip() != "":
            return str(v).strip()
    return default


# -------------------------
# MinIO Settings (browser/public vs docker/internal)
# -------------------------

# Browser/public base URL (what frontend/browser can reach)
MINIO_PUBLIC_BASE_URL = _env(
    "MINIO_PUBLIC_BASE_URL",
    default="http://localhost:9000",
)

# Internal base URL (what containers can reach)
MINIO_INTERNAL_BASE_URL = _env(
    "MINIO_INTERNAL_BASE_URL",
    default="http://minio:9000",
)

# Optional split form (used by your _minio_internal_url helper)
MINIO_INTERNAL_HOST = _env(
    "MINIO_INTERNAL_HOST",
    default="minio",
)
MINIO_INTERNAL_PORT = _env(
    "MINIO_INTERNAL_PORT",
    "MINIO_PORT",
    default="9000",
)

# MinIO client creds/settings (used by MinioManager)
MINIO_ENDPOINT = _env("MINIO_ENDPOINT", default="minio:9000")
MINIO_SECURE = _env("MINIO_SECURE", default="false").lower() == "true"
MINIO_ACCESS_KEY = _env("MINIO_ACCESS_KEY", "MINIO_ROOT_USER", default="")
MINIO_SECRET_KEY = _env("MINIO_SECRET_KEY", "MINIO_ROOT_PASSWORD", default="")

# Optional legacy/default bucket
MINIO_BUCKET_NAME_FIRE = _env("MINIO_BUCKET_NAME_FIRE", default="fire")


# -------------------------
# GeoServer Settings (REST internal vs browser/public)
# -------------------------

# Internal URL for REST calls inside docker (web -> geoserver)
GEOSERVER_BASE_URL_INTERNAL = _env(
    "GEOSERVER_BASE_URL_INTERNAL",
    "GEOSERVER_INTERNAL_BASE_URL",
    default="http://geoserver:8080/geoserver",
)


GEOSERVER_BASE_URL_INTERNAL = os.getenv("GEOSERVER_INTERNAL_BASE_URL", "http://geoserver:8080/geoserver")
GEOSERVER_BASE_URL_PUBLIC   = os.getenv("GEOSERVER_PUBLIC_BASE_URL", "http://localhost:8084/geoserver")

# Public URL for browser access (WMS/WMTS URLs returned by API)
GEOSERVER_BASE_URL_PUBLIC = _env(
    "GEOSERVER_BASE_URL_PUBLIC",
    "GEOSERVER_BASE_URL",
    "GEOSERVER_PUBLIC_BASE_URL",
    default="http://localhost:8084/geoserver",
)

# Admin creds
GEOSERVER_ADMIN_USER = _env(
    "GEOSERVER_ADMIN_USER",
    "GEOSERVER_USER",
    default="admin",
)
GEOSERVER_ADMIN_PASSWORD = _env(
    "GEOSERVER_ADMIN_PASSWORD",
    "GEOSERVER_PASSWORD",
    default="geoserver",
)

# Workspace
GEOSERVER_WORKSPACE = _env("GEOSERVER_WORKSPACE", default="fire")
GEOSERVER_STYLES_DIR = os.getenv("GEOSERVER_STYLES_DIR", "/app/geoserver_styles/styles")