# Generated by Django 6.0.2 on 2026-02-14 12:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IranCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'iran_counties',
            },
        ),
        migrations.CreateModel(
            name='IranForest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'iran_forests',
            },
        ),
        migrations.CreateModel(
            name='IranProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'iran_provinces',
            },
        ),
        migrations.CreateModel(
            name='IndexLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('minio_link', models.URLField(max_length=500)),
                ('index_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('satellite_name', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'index',
                'indexes': [models.Index(fields=['index_name', 'date'], name='index_index_n_f04802_idx'), models.Index(fields=['satellite_name', 'date'], name='index_satelli_5261b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('image_name', models.CharField(max_length=200)),
                ('minio_link', models.URLField(max_length=500)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'satellite_images',
                'indexes': [models.Index(fields=['satellite_name', 'date_time'], name='satellite_i_satelli_03485d_idx')],
            },
        ),
    ]
