# Generated by Django 6.0.2 on 2026-02-15 07:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AOI', max_length=120)),
                ('source', models.CharField(default='draw', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fire_aoi',
            },
        ),
        migrations.CreateModel(
            name='FireRiskArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('level', models.IntegerField(default=1)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'fire_risk_areas',
            },
        ),
    ]
