# Generated by Django 6.0.2 on 2026-02-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_aoi_fireriskarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aoi',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='fireriskarea',
            index=models.Index(fields=['name'], name='fire_risk_a_name_0a5997_idx'),
        ),
        migrations.AddIndex(
            model_name='fireriskarea',
            index=models.Index(fields=['level'], name='fire_risk_a_level_0ff842_idx'),
        ),
        migrations.AddIndex(
            model_name='irancounty',
            index=models.Index(fields=['name'], name='iran_counti_name_9e2561_idx'),
        ),
        migrations.AddIndex(
            model_name='iranforest',
            index=models.Index(fields=['name'], name='iran_forest_name_f51f69_idx'),
        ),
        migrations.AddIndex(
            model_name='iranprovince',
            index=models.Index(fields=['name'], name='iran_provin_name_483b41_idx'),
        ),
    ]
