# Generated by Django 6.0.2 on 2026-02-15 12:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0003_alter_aoi_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='iranforest',
            name='iran_forest_name_f51f69_idx',
        ),
        migrations.AlterField(
            model_name='fireriskarea',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='iranforest',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
        migrations.AlterModelTable(
            name='iranforest',
            table=None,
        ),
    ]
