# Generated by Django 6.0.2 on 2026-02-15 12:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0004_remove_iranforest_iran_forest_name_f51f69_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irancounty',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='iranprovince',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='iranforest',
            index=models.Index(fields=['name'], name='iran_forest_name_f51f69_idx'),
        ),
        migrations.AlterModelTable(
            name='iranforest',
            table='iran_forests',
        ),
    ]
