# Generated by Django 6.0.2 on 2026-02-15 12:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0005_alter_irancounty_geometry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireriskarea',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
