# Generated by Django 6.0.2 on 2026-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0006_alter_fireriskarea_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexlayer',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexlayer',
            name='geoserver_layer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='indexlayer',
            name='geoserver_store',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexlayer',
            name='geoserver_workspace',
            field=models.CharField(default='fire', max_length=100),
        ),
        migrations.AddField(
            model_name='indexlayer',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexlayer',
            name='minio_bucket',
            field=models.CharField(default='fire', max_length=100),
        ),
        migrations.AddField(
            model_name='indexlayer',
            name='minio_object',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='indexlayer',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('minio_ok', 'minio_ok'), ('geoserver_ok', 'geoserver_ok'), ('failed', 'failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='indexlayer',
            name='wms_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexlayer',
            name='wmts_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='geoserver_layer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='geoserver_store',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='geoserver_workspace',
            field=models.CharField(default='fire', max_length=100),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='minio_bucket',
            field=models.CharField(default='fire', max_length=100),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='minio_object',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('minio_ok', 'minio_ok'), ('geoserver_ok', 'geoserver_ok'), ('failed', 'failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='wms_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='wmts_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='indexlayer',
            index=models.Index(fields=['status'], name='index_status_7d055e_idx'),
        ),
        migrations.AddIndex(
            model_name='indexlayer',
            index=models.Index(fields=['is_published'], name='index_is_publ_50d530_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['status'], name='satellite_i_status_808b22_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['is_published'], name='satellite_i_is_publ_bd8b78_idx'),
        ),
    ]
