# Generated by Django 6.0.2 on 2026-02-08 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('access_level', models.CharField(choices=[('read', 'Read-only'), ('write', 'Read & Write')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_groups', to='users.user')),
            ],
            options={
                'db_table': 'access_groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.accessgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.user')),
            ],
            options={
                'db_table': 'group_members',
            },
        ),
        migrations.AddIndex(
            model_name='accessgroup',
            index=models.Index(fields=['name'], name='access_grou_name_5ee4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgroup',
            index=models.Index(fields=['access_level'], name='access_grou_access__c8db57_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uq_group_user'),
        ),
    ]
