# Generated by Django 6.0.2 on 2026-02-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accessgroup_groupmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('subsystem', models.CharField(choices=[('general', 'General'), ('fire', 'Fire'), ('flood', 'Flood'), ('earthquake', 'Earthquake')], default='general', max_length=20)),
                ('file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.user')),
            ],
            options={
                'db_table': 'users_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
